---
# see https://github.com/nextapps-de/flexsearch#tokenizer-prefix-search for options
tokenizer: "full" # strict, forward, reverse, full
custom_domain: "https://registry.perger.net"
fail_on_validation: true
searchableAttributes:
  - "prefLabel" # you should not delete this one
  - "notation"
  - "altLabel"
  - "hiddenLabel"
  - "example"
  - "definition"
  - "scopeNote"
ui:
  title: "Perger.net Registry" # Title is mandatory
  logo: "focus.png" # Path
  colors:
    skoHubWhite: "rgb(255, 255, 255)"
    skoHubDarkColor: "#014A69"
    skoHubMiddleColor: "#0070a0"
    skoHubLightColor: "#009CDF"
    skoHubThinColor: "rgb(55, 250, 210)"
    skoHubBlackColor: "rgb(5, 30, 30)"
    skoHubAction: "rgb(230, 0, 125)"
    skoHubNotice: "rgb(250, 180, 50)"
    skoHubDarkGrey: "#151515"
    skoHubMiddleGrey: "rgb(200, 200, 200)"
    skoHubLightGrey: "rgb(235, 235, 235)"
  fonts:
    regular:
      font_family: "Ubuntu"
      font_style: "normal"
      font_weight: 400
      name: "ubuntu-v20-latin-regular"
    bold:
      font_family: "Ubuntu"
      font_style: "normal"
      font_weight: 700
      name: "ubuntu-v20-latin-700"
